In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE
from random import shuffle

df = pd.read_csv("C:/Users/siddharth/Documents/progs/ml-1m/ml-1m/user1_ratings.csv")
print(df)

    User  MovieID  a1  a2  a3  a4  a5  a6  a7  a8  ...   a10  a11  a12  a13  \
0      1     1193   0   0   0   0   0   0   0   1  ...     0    0    0    0   
1      1      661   0   0   0   0   1   0   0   0  ...     0    1    0    1   
2      1      914   0   0   0   0   0   0   0   0  ...     0    1    0    0   
3      1     3408   0   0   0   0   0   0   0   1  ...     0    0    0    0   
4      1     2355   0   0   1   0   1   0   0   0  ...     0    0    0    1   
5      1     1197   1   1   1   0   0   0   0   0  ...     0    0    0    0   
6      1     1287   1   1   0   0   0   0   0   1  ...     0    0    0    0   
7      1     2804   0   0   1   0   0   0   0   1  ...     0    0    0    0   
8      1      594   0   0   0   0   1   0   0   0  ...     0    1    0    1   
9      1      919   0   1   0   0   1   0   0   1  ...     0    1    0    0   
10     1      595   0   0   0   0   1   0   0   0  ...     0    1    0    1   
11     1      938   0   0   0   0   0   0   0   0  .

In [2]:
data = tf.placeholder(tf.float32, [1,18,1])
target = tf.placeholder(tf.float32, [None, 2])
num_hidden = 18
cell = tf.nn.rnn_cell.LSTMCell(num_hidden,state_is_tuple=True)
val, state = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32)
val = tf.transpose(val, [1, 0, 2])
last = tf.gather(val, int(val.get_shape()[0]) - 1)
weight = tf.Variable(tf.truncated_normal([num_hidden, int(target.get_shape()[1])]))
bias = tf.Variable(tf.constant(0.1, shape=[target.get_shape()[1]]))
prediction = tf.nn.softmax(tf.matmul(last, weight) + bias)
cross_entropy = -tf.reduce_sum(target * tf.log(tf.clip_by_value(prediction,1e-10,1.0)))
optimizer = tf.train.AdamOptimizer()
minimize = optimizer.minimize(cross_entropy)
mistakes = tf.not_equal(tf.argmax(target, 1), tf.argmax(prediction, 1))
error = tf.reduce_mean(tf.cast(mistakes, tf.float32))
init_op = tf.initialize_all_variables()
sess = tf.Session()
sess.run(init_op)

Instructions for updating:
Use `tf.global_variables_initializer` instead.


In [3]:
df1 = df[['a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18']]
df2 = df[['like']]
dataset = df1.values
dataset = dataset.astype('float32')
dataset2 = df2.values
dataset2 = dataset2.astype('float32')
train_size = int(len(dataset) * 0.8)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size], dataset[train_size:len(dataset)]
train_op, test_op = dataset2[0:train_size], dataset2[train_size:len(dataset2)]
print(len(train), len(test))
print(dataset)
print(train)
print(test)
print(train_op)
print(test_op)


42 11
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.

In [4]:
print(sess.run(prediction,{data:[[[1],[0],[1],[1],[0],[1],[0],[1],[1],[0],[1],[0],[0],[0],[0],[0],[0],[0]]]}))



[[0.4968733  0.50312674]]


In [5]:
print(sess.run(prediction,{data:[[[1],[0],[1],[0],[0],[1],[0],[1],[0],[0],[1],[0],[0],[0],[0],[0],[0],[0]]]}))

[[0.49749362 0.5025064 ]]
