In [1]:
import tensorflow as tf
from keras import backend as K
from keras.layers import Layer, Dense, Dropout, LSTMCell, LSTM, GRU, RNN, Embedding
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as MSE
from random import shuffle

df = pd.read_csv("C:/Users/siddharth/Documents/progs/ml-1m/ml-1m/user1_ratings.csv")
print(df)

Using TensorFlow backend.


    User  MovieID  a1  a2  a3  a4  a5  a6  a7  a8  ...   a10  a11  a12  a13  \
0      1     1193   0   0   0   0   0   0   0   1  ...     0    0    0    0   
1      1      661   0   0   0   0   1   0   0   0  ...     0    1    0    1   
2      1      914   0   0   0   0   0   0   0   0  ...     0    1    0    0   
3      1     3408   0   0   0   0   0   0   0   1  ...     0    0    0    0   
4      1     2355   0   0   1   0   1   0   0   0  ...     0    0    0    1   
5      1     1197   1   1   1   0   0   0   0   0  ...     0    0    0    0   
6      1     1287   1   1   0   0   0   0   0   1  ...     0    0    0    0   
7      1     2804   0   0   1   0   0   0   0   1  ...     0    0    0    0   
8      1      594   0   0   0   0   1   0   0   0  ...     0    1    0    1   
9      1      919   0   1   0   0   1   0   0   1  ...     0    1    0    0   
10     1      595   0   0   0   0   1   0   0   0  ...     0    1    0    1   
11     1      938   0   0   0   0   0   0   0   0  .

In [2]:
df1 = df[['a1','a2','a3','a4','a5','a6','a7','a8','a9','a10','a11','a12','a13','a14','a15','a16','a17','a18']]
df2 = df[['like']]
dataset = df1.values
dataset = dataset.astype('float32')
dataset2 = df2.values
dataset2 = dataset2.astype('float32')
train_size = int(len(dataset) * 0.65)
test_size = len(dataset) - train_size
train, test = dataset[0:train_size], dataset[train_size:len(dataset)]
train_op, test_op = dataset2[0:train_size], dataset2[train_size:len(dataset2)]
print(len(train), len(test))
print(dataset)
print(train)
print(test)
print(train_op)
print(test_op)

34 19
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.

In [3]:
def create_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 200, output_dim = 50, input_length = input_length))
    model.add(LSTM(activation='sigmoid',units = 100, recurrent_activation='sigmoid'))
    model.add(Dense(1, activation='sigmoid'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model

model = create_model(len(train[0]))
hist = model.fit(train, train_op, epochs=100,batch_size=10)

scores = model.evaluate(dataset, dataset2, verbose=0)
print("Test accuracy : %.2f%%" %((scores[1]*100)))

Creating model...
Compiling...
Epoch 1/100
34/34 [==============================] - 3s 84ms/step - loss: 1.0278 - acc: 0.2353
Epoch 2/100
34/34 [==============================] - 0s 5ms/step - loss: 0.7927 - acc: 0.2353
Epoch 3/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6318 - acc: 0.7647
Epoch 4/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5524 - acc: 0.7647
Epoch 5/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5502 - acc: 0.7647
Epoch 6/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5523 - acc: 0.7647
Epoch 7/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5635 - acc: 0.7647
Epoch 8/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5620 - acc: 0.7647
Epoch 9/100
34/34 [==============================] - 0s 6ms/step - loss: 0.5570 - acc: 0.7647
Epoch 10/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5506 - acc: 0.7647
Epoch 11/100
34/34 [=======

Epoch 87/100
34/34 [==============================] - 0s 6ms/step - loss: 0.5473 - acc: 0.7647
Epoch 88/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5487 - acc: 0.7647
Epoch 89/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5406 - acc: 0.7647
Epoch 90/100
34/34 [==============================] - 0s 6ms/step - loss: 0.5460 - acc: 0.7647
Epoch 91/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5501 - acc: 0.7647
Epoch 92/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5516 - acc: 0.7647
Epoch 93/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5529 - acc: 0.7647
Epoch 94/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5472 - acc: 0.7647
Epoch 95/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5470 - acc: 0.7647
Epoch 96/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5485 - acc: 0.7647
Epoch 97/100
34/34 [==============================

In [4]:
from keras import activations
from keras import initializers
from keras import regularizers
from keras import constraints

class ModifiedLSTMCell(LSTMCell):

    def __init__(self, units,
                 activation='tanh',
                 recurrent_activation='sigmoid',
                 use_bias=True,
                 kernel_initializer='glorot_uniform',
                 recurrent_initializer='orthogonal',
                 bias_initializer='zeros',
                 unit_forget_bias=True,
                 kernel_regularizer=None,
                 recurrent_regularizer=None,
                 bias_regularizer=None,
                 kernel_constraint=None,
                 recurrent_constraint=None,
                 bias_constraint=None,
                 dropout=0.,
                 recurrent_dropout=0.,
                 implementation=1,
                 **kwargs):
        super(LSTMCell, self).__init__(**kwargs)
        self.units = units
        self.activation = activations.get(activation)
        self.recurrent_activation = activations.get(recurrent_activation)
        self.use_bias = use_bias

        self.kernel_initializer = initializers.get(kernel_initializer)
        self.recurrent_initializer = initializers.get(recurrent_initializer)
        self.bias_initializer = initializers.get(bias_initializer)
        self.unit_forget_bias = unit_forget_bias

        self.kernel_regularizer = regularizers.get(kernel_regularizer)
        self.recurrent_regularizer = regularizers.get(recurrent_regularizer)
        self.bias_regularizer = regularizers.get(bias_regularizer)

        self.kernel_constraint = constraints.get(kernel_constraint)
        self.recurrent_constraint = constraints.get(recurrent_constraint)
        self.bias_constraint = constraints.get(bias_constraint)

        self.dropout = min(1., max(0., dropout))
        self.recurrent_dropout = min(1., max(0., recurrent_dropout))
        self.implementation = implementation
        self.state_size = (self.units, self.units)
        self.output_size = self.units
        self._dropout_mask = None
        self._recurrent_dropout_mask = None

    def build(self, input_shape):
        input_dim = input_shape[-1]
        self.kernel = self.add_weight(shape=(input_dim, self.units * 4),
                                      name='kernel',
                                      initializer=self.kernel_initializer,
                                      regularizer=self.kernel_regularizer,
                                      constraint=self.kernel_constraint)
        self.recurrent_kernel = self.add_weight(
            shape=(self.units, self.units * 4),
            name='recurrent_kernel',
            initializer=self.recurrent_initializer,
            regularizer=self.recurrent_regularizer,
            constraint=self.recurrent_constraint)

        if self.use_bias:
            if self.unit_forget_bias:
                def bias_initializer(_, *args, **kwargs):
                    return K.concatenate([
                        self.bias_initializer((self.units,), *args, **kwargs),
                        initializers.Ones()((self.units,), *args, **kwargs),
                        self.bias_initializer((self.units * 2,), *args, **kwargs),
                    ])
            else:
                bias_initializer = self.bias_initializer
            self.bias = self.add_weight(shape=(self.units * 4,),
                                        name='bias',
                                        initializer=bias_initializer,
                                        regularizer=self.bias_regularizer,
                                        constraint=self.bias_constraint)
        else:
            self.bias = None

        self.kernel_i = self.kernel[:, :self.units]
        self.kernel_f = self.kernel[:, self.units: self.units * 2]
        self.kernel_c = self.kernel[:, self.units * 2: self.units * 3]
        self.kernel_o = self.kernel[:, self.units * 3:]

        self.recurrent_kernel_i = self.recurrent_kernel[:, :self.units]
        self.recurrent_kernel_f = (
            self.recurrent_kernel[:, self.units: self.units * 2])
        self.recurrent_kernel_c = (
            self.recurrent_kernel[:, self.units * 2: self.units * 3])
        self.recurrent_kernel_o = self.recurrent_kernel[:, self.units * 3:]

        if self.use_bias:
            self.bias_i = self.bias[:self.units]
            self.bias_f = self.bias[self.units: self.units * 2]
            self.bias_c = self.bias[self.units * 2: self.units * 3]
            self.bias_o = self.bias[self.units * 3:]
        else:
            self.bias_i = None
            self.bias_f = None
            self.bias_c = None
            self.bias_o = None
        self.built = True

    def call(self, inputs, states, training=None):
        if 0 < self.dropout < 1 and self._dropout_mask is None:
            self._dropout_mask = _generate_dropout_mask(
                K.ones_like(inputs),
                self.dropout,
                training=training,
                count=4)
        if (0 < self.recurrent_dropout < 1 and
                self._recurrent_dropout_mask is None):
            self._recurrent_dropout_mask = _generate_dropout_mask(
                K.ones_like(states[0]),
                self.recurrent_dropout,
                training=training,
                count=4)

        # dropout matrices for input units
        dp_mask = self._dropout_mask
        # dropout matrices for recurrent units
        rec_dp_mask = self._recurrent_dropout_mask

        h_tm1 = states[0]  # previous memory state
        c_tm1 = states[1]  # previous carry state

        if self.implementation == 1:
            if 0 < self.dropout < 1.:
                inputs_i = inputs * dp_mask[0]
                inputs_f = inputs * dp_mask[1]
                inputs_c = inputs * dp_mask[2]
                inputs_o = inputs * dp_mask[3]
            else:
                inputs_i = inputs
                inputs_f = inputs
                inputs_c = inputs
                inputs_o = inputs
            x_i = K.dot(inputs_i, self.kernel_i)
            x_f = K.dot(inputs_f, self.kernel_f)
            x_c = K.dot(inputs_c, self.kernel_c)
            x_o = K.dot(inputs_o, self.kernel_o)
            if self.use_bias:
                x_i = K.bias_add(x_i, self.bias_i)
                x_f = K.bias_add(x_f, self.bias_f)
                x_c = K.bias_add(x_c, self.bias_c)
                x_o = K.bias_add(x_o, self.bias_o)

            if 0 < self.recurrent_dropout < 1.:
                h_tm1_i = h_tm1 * rec_dp_mask[0]
                h_tm1_f = h_tm1 * rec_dp_mask[1]
                h_tm1_c = h_tm1 * rec_dp_mask[2]
                h_tm1_o = h_tm1 * rec_dp_mask[3]
            else:
                h_tm1_i = h_tm1
                h_tm1_f = h_tm1
                h_tm1_c = h_tm1
                h_tm1_o = h_tm1
            i = self.recurrent_activation(x_i + K.dot(h_tm1_i,
                                                      self.recurrent_kernel_i))
            f = 0
            c = f * c_tm1 + i * self.activation(x_c + K.dot(h_tm1_c,
                                                            self.recurrent_kernel_c))
            o = self.recurrent_activation(x_o + K.dot(h_tm1_o,
                                                      self.recurrent_kernel_o))
        else:
            if 0. < self.dropout < 1.:
                inputs *= dp_mask[0]
            z = K.dot(inputs, self.kernel)
            if 0. < self.recurrent_dropout < 1.:
                h_tm1 *= rec_dp_mask[0]
            z += K.dot(h_tm1, self.recurrent_kernel)
            if self.use_bias:
                z = K.bias_add(z, self.bias)

            z0 = z[:, :self.units]
            z1 = z[:, self.units: 2 * self.units]
            z2 = z[:, 2 * self.units: 3 * self.units]
            z3 = z[:, 3 * self.units:]

            i = self.recurrent_activation(z0)
            f = self.recurrent_activation(z1)
            c = f * c_tm1 + i * self.activation(z2)
            o = self.recurrent_activation(z3)

        h = o * self.activation(c)
        if 0 < self.dropout + self.recurrent_dropout:
            if training is None:
                h._uses_learning_phase = True
        return h, [h, c]

    def get_config(self):
        config = {'units': self.units,
                  'activation': activations.serialize(self.activation),
                  'recurrent_activation':
                      activations.serialize(self.recurrent_activation),
                  'use_bias': self.use_bias,
                  'kernel_initializer':
                      initializers.serialize(self.kernel_initializer),
                  'recurrent_initializer':
                      initializers.serialize(self.recurrent_initializer),
                  'bias_initializer': initializers.serialize(self.bias_initializer),
                  'unit_forget_bias': self.unit_forget_bias,
                  'kernel_regularizer':
                      regularizers.serialize(self.kernel_regularizer),
                  'recurrent_regularizer':
                      regularizers.serialize(self.recurrent_regularizer),
                  'bias_regularizer': regularizers.serialize(self.bias_regularizer),
                  'kernel_constraint': constraints.serialize(self.kernel_constraint),
                  'recurrent_constraint':
                      constraints.serialize(self.recurrent_constraint),
                  'bias_constraint': constraints.serialize(self.bias_constraint),
                  'dropout': self.dropout,
                  'recurrent_dropout': self.recurrent_dropout,
                  'implementation': self.implementation}
        base_config = super(LSTMCell, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

In [9]:
class ModifiedLSTM(LSTM):

    def __init__(self, units,
                 activation='tanh',
                 recurrent_activation='sigmoid',
                 use_bias=True,
                 kernel_initializer='glorot_uniform',
                 recurrent_initializer='orthogonal',
                 bias_initializer='zeros',
                 unit_forget_bias=True,
                 kernel_regularizer=None,
                 recurrent_regularizer=None,
                 bias_regularizer=None,
                 activity_regularizer=None,
                 kernel_constraint=None,
                 recurrent_constraint=None,
                 bias_constraint=None,
                 dropout=0.,
                 recurrent_dropout=0.,
                 implementation=1,
                 return_sequences=False,
                 return_state=False,
                 go_backwards=False,
                 stateful=False,
                 unroll=False,
                 **kwargs):
        if implementation == 0:
            warnings.warn('`implementation=0` has been deprecated, '
                          'and now defaults to `implementation=1`.'
                          'Please update your layer call.')
        if K.backend() == 'theano' and (dropout or recurrent_dropout):
            warnings.warn(
                'RNN dropout is no longer supported with the Theano backend '
                'due to technical limitations. '
                'You can either set `dropout` and `recurrent_dropout` to 0, '
                'or use the TensorFlow backend.')
            dropout = 0.
            recurrent_dropout = 0.

        cell = ModifiedLSTMCell(units,
                        activation=activation,
                        recurrent_activation=recurrent_activation,
                        use_bias=use_bias,
                        kernel_initializer=kernel_initializer,
                        recurrent_initializer=recurrent_initializer,
                        unit_forget_bias=unit_forget_bias,
                        bias_initializer=bias_initializer,
                        kernel_regularizer=kernel_regularizer,
                        recurrent_regularizer=recurrent_regularizer,
                        bias_regularizer=bias_regularizer,
                        kernel_constraint=kernel_constraint,
                        recurrent_constraint=recurrent_constraint,
                        bias_constraint=bias_constraint,
                        dropout=dropout,
                        recurrent_dropout=recurrent_dropout,
                        implementation=implementation)
        super(LSTM, self).__init__(cell,
                                   return_sequences=return_sequences,
                                   return_state=return_state,
                                   go_backwards=go_backwards,
                                   stateful=stateful,
                                   unroll=unroll,
                                   **kwargs)
        self.activity_regularizer = regularizers.get(activity_regularizer)

    def call(self, inputs, mask=None, training=None, initial_state=None):
        self.cell._dropout_mask = None
        self.cell._recurrent_dropout_mask = None
        return super(LSTM, self).call(inputs,
                                      mask=mask,
                                      training=training,
                                      initial_state=initial_state)

    @property
    def units(self):
        return self.cell.units

    @property
    def activation(self):
        return self.cell.activation

    @property
    def recurrent_activation(self):
        return self.cell.recurrent_activation

    @property
    def use_bias(self):
        return self.cell.use_bias

    @property
    def kernel_initializer(self):
        return self.cell.kernel_initializer

    @property
    def recurrent_initializer(self):
        return self.cell.recurrent_initializer

    @property
    def bias_initializer(self):
        return self.cell.bias_initializer

    @property
    def unit_forget_bias(self):
        return self.cell.unit_forget_bias

    @property
    def kernel_regularizer(self):
        return self.cell.kernel_regularizer

    @property
    def recurrent_regularizer(self):
        return self.cell.recurrent_regularizer

    @property
    def bias_regularizer(self):
        return self.cell.bias_regularizer

    @property
    def kernel_constraint(self):
        return self.cell.kernel_constraint

    @property
    def recurrent_constraint(self):
        return self.cell.recurrent_constraint

    @property
    def bias_constraint(self):
        return self.cell.bias_constraint

    @property
    def dropout(self):
        return self.cell.dropout

    @property
    def recurrent_dropout(self):
        return self.cell.recurrent_dropout

    @property
    def implementation(self):
        return self.cell.implementation

    def get_config(self):
        config = {'units': self.units,
                  'activation': activations.serialize(self.activation),
                  'recurrent_activation':
                      activations.serialize(self.recurrent_activation),
                  'use_bias': self.use_bias,
                  'kernel_initializer':
                      initializers.serialize(self.kernel_initializer),
                  'recurrent_initializer':
                      initializers.serialize(self.recurrent_initializer),
                  'bias_initializer': initializers.serialize(self.bias_initializer),
                  'unit_forget_bias': self.unit_forget_bias,
                  'kernel_regularizer':
                      regularizers.serialize(self.kernel_regularizer),
                  'recurrent_regularizer':
                      regularizers.serialize(self.recurrent_regularizer),
                  'bias_regularizer': regularizers.serialize(self.bias_regularizer),
                  'activity_regularizer':
                      regularizers.serialize(self.activity_regularizer),
                  'kernel_constraint': constraints.serialize(self.kernel_constraint),
                  'recurrent_constraint':
                      constraints.serialize(self.recurrent_constraint),
                  'bias_constraint': constraints.serialize(self.bias_constraint),
                  'dropout': self.dropout,
                  'recurrent_dropout': self.recurrent_dropout,
                  'implementation': self.implementation}
        base_config = super(LSTM, self).get_config()
        del base_config['cell']
        return dict(list(base_config.items()) + list(config.items()))

    @classmethod
    def from_config(cls, config):
        if 'implementation' in config and config['implementation'] == 0:
            config['implementation'] = 1
        return cls(**config)


def _generate_dropout_mask(ones, rate, training=None, count=1):
    def dropped_inputs():
        return K.dropout(ones, rate)

    if count > 1:
        return [K.in_train_phase(
            dropped_inputs,
            ones,
            training=training) for _ in range(count)]
    return K.in_train_phase(
        dropped_inputs,
        ones,
        training=training)


def _standardize_args(inputs, initial_state, constants, num_constants):
    
    if isinstance(inputs, list):
        assert initial_state is None and constants is None
        if num_constants is not None:
            constants = inputs[-num_constants:]
            inputs = inputs[:-num_constants]
        if len(inputs) > 1:
            initial_state = inputs[1:]
        inputs = inputs[0]

    def to_list_or_none(x):
        if x is None or isinstance(x, list):
            return x
        if isinstance(x, tuple):
            return list(x)
        return [x]

    initial_state = to_list_or_none(initial_state)
    constants = to_list_or_none(constants)

    return inputs, initial_state, constants

In [12]:
def create_my_model(input_length):
    print ('Creating model...')
    model = Sequential()
    model.add(Embedding(input_dim = 100, output_dim = 50, input_length = input_length))
    model.add(Dropout(0.5))
    model.add(ModifiedLSTM(activation='sigmoid',units = input_length, recurrent_activation='tanh'))
    model.add(Dropout(0.5))
    model.add(Dense(1, activation='hard_sigmoid'))

    print ('Compiling...')
    model.compile(loss='binary_crossentropy',
                  optimizer='adam',
                  metrics=['accuracy'])
    return model

model = create_my_model(len(train[0]))
hist = model.fit(train, train_op, epochs=100,batch_size=10)

scores = model.evaluate(dataset, dataset2, verbose=0)
print("Test accuracy : %.2f%%" %((scores[1]*100)))

Creating model...
Compiling...
Epoch 1/100
34/34 [==============================] - 1s 41ms/step - loss: 0.6885 - acc: 0.6471
Epoch 2/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6803 - acc: 0.7353
Epoch 3/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6736 - acc: 0.7647
Epoch 4/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6709 - acc: 0.7647
Epoch 5/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6652 - acc: 0.7647
Epoch 6/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6541 - acc: 0.7647
Epoch 7/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6483 - acc: 0.7647
Epoch 8/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6427 - acc: 0.7647
Epoch 9/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6251 - acc: 0.7647
Epoch 10/100
34/34 [==============================] - 0s 5ms/step - loss: 0.6115 - acc: 0.7647
Epoch 11/100
34/34 [=======

34/34 [==============================] - 0s 5ms/step - loss: 0.5605 - acc: 0.7647
Epoch 87/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5879 - acc: 0.7647
Epoch 88/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5501 - acc: 0.7647
Epoch 89/100
34/34 [==============================] - 0s 5ms/step - loss: 0.5623 - acc: 0.7647
Epoch 90/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5497 - acc: 0.7647
Epoch 91/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5706 - acc: 0.7647
Epoch 92/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5862 - acc: 0.7647
Epoch 93/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5523 - acc: 0.7647
Epoch 94/100
34/34 [==============================] - 0s 4ms/step - loss: 0.4902 - acc: 0.7647
Epoch 95/100
34/34 [==============================] - 0s 4ms/step - loss: 0.5277 - acc: 0.7647
Epoch 96/100
34/34 [==============================] - 0s 4ms/st